In [195]:
import numpy as np
a=np.ones((2,3))
print(a)

b=np.full((3,2),2)
print(b)

result=np.matmul(a,b)
print(result)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


In [196]:
# Find the determinant

c=np.identity(3)
np.linalg.det(c)

np.float64(1.0)

In [197]:
# statistics with numpy

stats=np.array([[1,2,3],[4,5,6]])
print(stats)

print(np.min(stats))
print(np.max(stats))
print(np.min(stats,axis=0))
print(np.min(stats,axis=1))

print(np.max(stats,axis=0))
print(np.max(stats,axis=1))

print(np.sum(stats))
print(np.sum((stats),axis=0))
print(np.sum((stats),axis=1))

[[1 2 3]
 [4 5 6]]
1
6
[1 2 3]
[1 4]
[4 5 6]
[3 6]
21
[5 7 9]
[ 6 15]


In [198]:
# Reorganizing Arrays

before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after=before.reshape((1,8))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]]


In [199]:
# Vertically Stacking Vectors

v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

print(np.vstack([v1,v2]))
print(np.vstack([v1,v2,v1,v2]))

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [200]:
# Horizontal Stack

h1=np.ones((3,3))
h2=np.zeros((3,3))
print(h1)
print(h2)

print(np.hstack((h1,h2)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]


In [201]:
from google.colab import drive
drive.mount('/content/drive')
import numpy as np

data = np.genfromtxt('/content/drive/My Drive/data.txt', delimiter=',', invalid_raise=False)
print(data)




Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
[[ 12.  45.  34.  22.  89.  67.  55.  90.  87.  77.  99.  67.  36.  54.
   24.  13.  10.   8.   6.  52.]
 [ 76.  97.  87.  51.  49.  88.   3.  39.  80.  11.  19.  29.  27.  46.
   33.  44.  55.  66. 100.   1.]]
